# Generated by Django 5.2.7 on 2025-10-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.CharField(max_length=70, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(unique=True)),
            ],
        ),
    ]
